Repository oaaky/SE_Fall20_Project-1, pull requests merged in 2020-09, with the labels that each got.

#9 fix in-memory dict and log format, flush on sublime close
  code/SublimePlugin/plugin_sublime.py
Labels: enhancement

#37 add unit test files and modified dir structure
  code/SublimePlugin/codeTime.py
  codeTime.py
  test/test_codeTime.py
  unittesting.json
Labels: enhancement, test

#55 add travis build badge, fixed linter errors
  README.md
  code/SublimePlugin/codeTime.py
Labels: documentation

#56 Add zenodo DOI badge
  README.md
Labels: documentation

#64 Add installation and usage sections in README.md
  README.md
Labels: documentation

#76 Add Setup and test run instructions to README.md
  README.md
Labels: documentation
